name: CI - Build and Test
run-name: Triggered by ${{ github.actor }} on ${{ github.event_name }}
on: [push, workflow_dispatch]
jobs:
  Build and Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app
        run: python main.py

      - name: Run tests
        run: python -m pytest
